/*
 *
 * Automatically generated file; DO NOT EDIT.
 * Configuration
 *
 */
#define CONFIG_WATCHPOINT 1
#define CONFIG_ETRACE 1
#define CONFIG_DIFFTEST 1
#define CONFIG_TRACE_END 10000
#define CONFIG_MTRACE_START 0x80000000
#define CONFIG_FTRACE 1
#define CONFIG_MTRACE 1
#define CONFIG_DTRACE 1
#define CONFIG_MTRACE_END 0x88000000
#define CONFIG_TRACE_START 0
#define CONFIG_TRACE 1
